### ISSUE TITLE
Update app icon with curved version

### ISSUE THREAD

**Issue by timbroder** [Kidfund/building.kid.fund#13]
![image](https://user-images.githubusercontent.com/121503/35043909-5da3acd4-fb5c-11e7-8077-09aa86b4db4e.png)

**Comment by mrh-is** [comment]
TBH I like the square version here ¯\\\_(ツ)_/¯

But I'm not opposed to the [squircle](https://en.wikipedia.org/wiki/Squircle), if we're more into that.

**Comment by timbroder** [comment]
TIL what a `Squircle` is. I agree. Can reopen if feedback changes
